# CMake generated Testfile for 
# Source directory: D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests
# Build directory: D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.List]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ListTest.cmake")
  set_tests_properties([=[CMake.List]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;14;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.List]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ListTest.cmake")
  set_tests_properties([=[CMake.List]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;14;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.List]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ListTest.cmake")
  set_tests_properties([=[CMake.List]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;14;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.List]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ListTest.cmake")
  set_tests_properties([=[CMake.List]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;14;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.List]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.VariableWatch]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/VariableWatchTest.cmake")
  set_tests_properties([=[CMake.VariableWatch]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;15;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.VariableWatch]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/VariableWatchTest.cmake")
  set_tests_properties([=[CMake.VariableWatch]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;15;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.VariableWatch]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/VariableWatchTest.cmake")
  set_tests_properties([=[CMake.VariableWatch]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;15;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.VariableWatch]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/VariableWatchTest.cmake")
  set_tests_properties([=[CMake.VariableWatch]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;15;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.VariableWatch]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.Include]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/IncludeTest.cmake")
  set_tests_properties([=[CMake.Include]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;16;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.Include]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/IncludeTest.cmake")
  set_tests_properties([=[CMake.Include]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;16;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.Include]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/IncludeTest.cmake")
  set_tests_properties([=[CMake.Include]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;16;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.Include]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/IncludeTest.cmake")
  set_tests_properties([=[CMake.Include]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;16;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.Include]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.FindBase]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/FindBaseTest.cmake")
  set_tests_properties([=[CMake.FindBase]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;17;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.FindBase]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/FindBaseTest.cmake")
  set_tests_properties([=[CMake.FindBase]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;17;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.FindBase]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/FindBaseTest.cmake")
  set_tests_properties([=[CMake.FindBase]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;17;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.FindBase]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/FindBaseTest.cmake")
  set_tests_properties([=[CMake.FindBase]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;17;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.FindBase]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.Toolchain]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ToolchainTest.cmake")
  set_tests_properties([=[CMake.Toolchain]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;18;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.Toolchain]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ToolchainTest.cmake")
  set_tests_properties([=[CMake.Toolchain]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;18;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.Toolchain]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ToolchainTest.cmake")
  set_tests_properties([=[CMake.Toolchain]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;18;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.Toolchain]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ToolchainTest.cmake")
  set_tests_properties([=[CMake.Toolchain]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;18;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.Toolchain]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.GetFilenameComponentRealpath]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/GetFilenameComponentRealpathTest.cmake")
  set_tests_properties([=[CMake.GetFilenameComponentRealpath]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;19;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.GetFilenameComponentRealpath]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/GetFilenameComponentRealpathTest.cmake")
  set_tests_properties([=[CMake.GetFilenameComponentRealpath]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;19;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.GetFilenameComponentRealpath]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/GetFilenameComponentRealpathTest.cmake")
  set_tests_properties([=[CMake.GetFilenameComponentRealpath]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;19;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.GetFilenameComponentRealpath]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/GetFilenameComponentRealpathTest.cmake")
  set_tests_properties([=[CMake.GetFilenameComponentRealpath]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;19;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.GetFilenameComponentRealpath]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.Version]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/VersionTest.cmake")
  set_tests_properties([=[CMake.Version]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;20;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.Version]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/VersionTest.cmake")
  set_tests_properties([=[CMake.Version]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;20;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.Version]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/VersionTest.cmake")
  set_tests_properties([=[CMake.Version]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;20;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.Version]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/VersionTest.cmake")
  set_tests_properties([=[CMake.Version]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;20;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.Version]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.Message]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/MessageTest.cmake")
  set_tests_properties([=[CMake.Message]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;21;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.Message]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/MessageTest.cmake")
  set_tests_properties([=[CMake.Message]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;21;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.Message]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/MessageTest.cmake")
  set_tests_properties([=[CMake.Message]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;21;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.Message]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/MessageTest.cmake")
  set_tests_properties([=[CMake.Message]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;21;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.Message]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.File]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/FileTest.cmake")
  set_tests_properties([=[CMake.File]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;22;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.File]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/FileTest.cmake")
  set_tests_properties([=[CMake.File]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;22;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.File]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/FileTest.cmake")
  set_tests_properties([=[CMake.File]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;22;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.File]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/FileTest.cmake")
  set_tests_properties([=[CMake.File]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;22;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.File]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.ImplicitLinkInfo]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ImplicitLinkInfoTest.cmake")
  set_tests_properties([=[CMake.ImplicitLinkInfo]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;23;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.ImplicitLinkInfo]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ImplicitLinkInfoTest.cmake")
  set_tests_properties([=[CMake.ImplicitLinkInfo]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;23;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.ImplicitLinkInfo]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ImplicitLinkInfoTest.cmake")
  set_tests_properties([=[CMake.ImplicitLinkInfo]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;23;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.ImplicitLinkInfo]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ImplicitLinkInfoTest.cmake")
  set_tests_properties([=[CMake.ImplicitLinkInfo]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;23;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.ImplicitLinkInfo]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.ModuleNotices]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ModuleNoticesTest.cmake")
  set_tests_properties([=[CMake.ModuleNotices]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;24;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.ModuleNotices]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ModuleNoticesTest.cmake")
  set_tests_properties([=[CMake.ModuleNotices]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;24;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.ModuleNotices]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ModuleNoticesTest.cmake")
  set_tests_properties([=[CMake.ModuleNotices]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;24;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.ModuleNotices]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ModuleNoticesTest.cmake")
  set_tests_properties([=[CMake.ModuleNotices]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;24;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.ModuleNotices]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.GetProperty]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/GetPropertyTest.cmake")
  set_tests_properties([=[CMake.GetProperty]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;25;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.GetProperty]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/GetPropertyTest.cmake")
  set_tests_properties([=[CMake.GetProperty]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;25;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.GetProperty]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/GetPropertyTest.cmake")
  set_tests_properties([=[CMake.GetProperty]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;25;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.GetProperty]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/GetPropertyTest.cmake")
  set_tests_properties([=[CMake.GetProperty]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;25;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.GetProperty]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.If]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/IfTest.cmake")
  set_tests_properties([=[CMake.If]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;26;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.If]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/IfTest.cmake")
  set_tests_properties([=[CMake.If]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;26;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.If]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/IfTest.cmake")
  set_tests_properties([=[CMake.If]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;26;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.If]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/IfTest.cmake")
  set_tests_properties([=[CMake.If]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;26;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.If]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.String]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/StringTest.cmake")
  set_tests_properties([=[CMake.String]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;27;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.String]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/StringTest.cmake")
  set_tests_properties([=[CMake.String]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;27;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.String]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/StringTest.cmake")
  set_tests_properties([=[CMake.String]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;27;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.String]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/StringTest.cmake")
  set_tests_properties([=[CMake.String]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;27;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.String]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.Math]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/MathTest.cmake")
  set_tests_properties([=[CMake.Math]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;28;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.Math]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/MathTest.cmake")
  set_tests_properties([=[CMake.Math]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;28;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.Math]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/MathTest.cmake")
  set_tests_properties([=[CMake.Math]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;28;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.Math]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/MathTest.cmake")
  set_tests_properties([=[CMake.Math]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;28;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.Math]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.CMakeMinimumRequired]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/CMakeMinimumRequiredTest.cmake")
  set_tests_properties([=[CMake.CMakeMinimumRequired]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;29;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.CMakeMinimumRequired]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/CMakeMinimumRequiredTest.cmake")
  set_tests_properties([=[CMake.CMakeMinimumRequired]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;29;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.CMakeMinimumRequired]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/CMakeMinimumRequiredTest.cmake")
  set_tests_properties([=[CMake.CMakeMinimumRequired]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;29;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.CMakeMinimumRequired]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/CMakeMinimumRequiredTest.cmake")
  set_tests_properties([=[CMake.CMakeMinimumRequired]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;29;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.CMakeMinimumRequired]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.CompilerIdVendor]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/CompilerIdVendorTest.cmake")
  set_tests_properties([=[CMake.CompilerIdVendor]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;30;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.CompilerIdVendor]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/CompilerIdVendorTest.cmake")
  set_tests_properties([=[CMake.CompilerIdVendor]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;30;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.CompilerIdVendor]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/CompilerIdVendorTest.cmake")
  set_tests_properties([=[CMake.CompilerIdVendor]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;30;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.CompilerIdVendor]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/CompilerIdVendorTest.cmake")
  set_tests_properties([=[CMake.CompilerIdVendor]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;30;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.CompilerIdVendor]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.ProcessorCount]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-DKWSYS_TEST_EXE=D:/Project/Application/FaceRecognitionPart/myenv/Source/kwsys/Debug/cmsysTestsCxx.exe" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ProcessorCountTest.cmake")
  set_tests_properties([=[CMake.ProcessorCount]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;31;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.ProcessorCount]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-DKWSYS_TEST_EXE=D:/Project/Application/FaceRecognitionPart/myenv/Source/kwsys/Release/cmsysTestsCxx.exe" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ProcessorCountTest.cmake")
  set_tests_properties([=[CMake.ProcessorCount]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;31;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.ProcessorCount]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-DKWSYS_TEST_EXE=D:/Project/Application/FaceRecognitionPart/myenv/Source/kwsys/MinSizeRel/cmsysTestsCxx.exe" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ProcessorCountTest.cmake")
  set_tests_properties([=[CMake.ProcessorCount]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;31;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.ProcessorCount]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-DKWSYS_TEST_EXE=D:/Project/Application/FaceRecognitionPart/myenv/Source/kwsys/RelWithDebInfo/cmsysTestsCxx.exe" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/ProcessorCountTest.cmake")
  set_tests_properties([=[CMake.ProcessorCount]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;31;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.ProcessorCount]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.PushCheckState]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/PushCheckStateTest.cmake")
  set_tests_properties([=[CMake.PushCheckState]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;32;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.PushCheckState]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/PushCheckStateTest.cmake")
  set_tests_properties([=[CMake.PushCheckState]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;32;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.PushCheckState]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/PushCheckStateTest.cmake")
  set_tests_properties([=[CMake.PushCheckState]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;32;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.PushCheckState]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/PushCheckStateTest.cmake")
  set_tests_properties([=[CMake.PushCheckState]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;32;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.PushCheckState]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.While]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/WhileTest.cmake")
  set_tests_properties([=[CMake.While]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;33;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.While]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/WhileTest.cmake")
  set_tests_properties([=[CMake.While]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;33;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.While]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/WhileTest.cmake")
  set_tests_properties([=[CMake.While]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;33;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.While]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/WhileTest.cmake")
  set_tests_properties([=[CMake.While]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;33;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.While]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.FileUpload]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/FileUploadTest.cmake")
  set_tests_properties([=[CMake.FileUpload]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;35;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.FileUpload]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/FileUploadTest.cmake")
  set_tests_properties([=[CMake.FileUpload]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;35;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.FileUpload]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/FileUploadTest.cmake")
  set_tests_properties([=[CMake.FileUpload]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;35;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.FileUpload]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/FileUploadTest.cmake")
  set_tests_properties([=[CMake.FileUpload]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;35;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.FileUpload]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.EndStuff]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-Ddir:STRING=D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/EndStuffTest" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/EndStuffTest.cmake")
  set_tests_properties([=[CMake.EndStuff]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;40;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.EndStuff]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-Ddir:STRING=D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/EndStuffTest" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/EndStuffTest.cmake")
  set_tests_properties([=[CMake.EndStuff]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;40;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.EndStuff]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-Ddir:STRING=D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/EndStuffTest" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/EndStuffTest.cmake")
  set_tests_properties([=[CMake.EndStuff]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;40;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.EndStuff]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-Ddir:STRING=D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/EndStuffTest" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/EndStuffTest.cmake")
  set_tests_properties([=[CMake.EndStuff]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;40;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.EndStuff]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.GetPrerequisites]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-DConfiguration:STRING=Debug" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/GetPrerequisitesTest.cmake")
  set_tests_properties([=[CMake.GetPrerequisites]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;42;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.GetPrerequisites]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-DConfiguration:STRING=Release" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/GetPrerequisitesTest.cmake")
  set_tests_properties([=[CMake.GetPrerequisites]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;42;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.GetPrerequisites]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-DConfiguration:STRING=MinSizeRel" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/GetPrerequisitesTest.cmake")
  set_tests_properties([=[CMake.GetPrerequisites]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;42;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.GetPrerequisites]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-DConfiguration:STRING=RelWithDebInfo" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/GetPrerequisitesTest.cmake")
  set_tests_properties([=[CMake.GetPrerequisites]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;42;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.GetPrerequisites]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMake.PolicyCheck]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-DCMake_BINARY_DIR:PATH=D:/Project/Application/FaceRecognitionPart/myenv" "-DCMake_SOURCE_DIR:PATH=D:/Project/Application/FaceRecognitionPart/cmake-3.27.7" "-DGIT_EXECUTABLE:STRING=C:/Program Files/Git/cmd/git.exe" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/PolicyCheckTest.cmake")
  set_tests_properties([=[CMake.PolicyCheck]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;50;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMake.PolicyCheck]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-DCMake_BINARY_DIR:PATH=D:/Project/Application/FaceRecognitionPart/myenv" "-DCMake_SOURCE_DIR:PATH=D:/Project/Application/FaceRecognitionPart/cmake-3.27.7" "-DGIT_EXECUTABLE:STRING=C:/Program Files/Git/cmd/git.exe" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/PolicyCheckTest.cmake")
  set_tests_properties([=[CMake.PolicyCheck]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;50;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMake.PolicyCheck]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-DCMake_BINARY_DIR:PATH=D:/Project/Application/FaceRecognitionPart/myenv" "-DCMake_SOURCE_DIR:PATH=D:/Project/Application/FaceRecognitionPart/cmake-3.27.7" "-DGIT_EXECUTABLE:STRING=C:/Program Files/Git/cmd/git.exe" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/PolicyCheckTest.cmake")
  set_tests_properties([=[CMake.PolicyCheck]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;50;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMake.PolicyCheck]=] "D:/Project/Application/FaceRecognitionPart/myenv/bin/cmake" "-DCMake_BINARY_DIR:PATH=D:/Project/Application/FaceRecognitionPart/myenv" "-DCMake_SOURCE_DIR:PATH=D:/Project/Application/FaceRecognitionPart/cmake-3.27.7" "-DGIT_EXECUTABLE:STRING=C:/Program Files/Git/cmd/git.exe" "-P" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeTests/PolicyCheckTest.cmake")
  set_tests_properties([=[CMake.PolicyCheck]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;7;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;50;AddCMakeTest;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeTests/CMakeLists.txt;0;")
else()
  add_test([=[CMake.PolicyCheck]=] NOT_AVAILABLE)
endif()
