# CMake generated Testfile for 
# Source directory: D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib
# Build directory: D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testArgumentParser]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testArgumentParser")
  set_tests_properties([=[CMakeLib.testArgumentParser]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testArgumentParser]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testArgumentParser")
  set_tests_properties([=[CMakeLib.testArgumentParser]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testArgumentParser]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testArgumentParser")
  set_tests_properties([=[CMakeLib.testArgumentParser]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testArgumentParser]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testArgumentParser")
  set_tests_properties([=[CMakeLib.testArgumentParser]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testArgumentParser]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testCTestBinPacker]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testCTestBinPacker")
  set_tests_properties([=[CMakeLib.testCTestBinPacker]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testCTestBinPacker]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testCTestBinPacker")
  set_tests_properties([=[CMakeLib.testCTestBinPacker]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testCTestBinPacker]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testCTestBinPacker")
  set_tests_properties([=[CMakeLib.testCTestBinPacker]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testCTestBinPacker]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testCTestBinPacker")
  set_tests_properties([=[CMakeLib.testCTestBinPacker]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testCTestBinPacker]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testCTestResourceAllocator]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testCTestResourceAllocator")
  set_tests_properties([=[CMakeLib.testCTestResourceAllocator]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testCTestResourceAllocator]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testCTestResourceAllocator")
  set_tests_properties([=[CMakeLib.testCTestResourceAllocator]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testCTestResourceAllocator]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testCTestResourceAllocator")
  set_tests_properties([=[CMakeLib.testCTestResourceAllocator]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testCTestResourceAllocator]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testCTestResourceAllocator")
  set_tests_properties([=[CMakeLib.testCTestResourceAllocator]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testCTestResourceAllocator]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testCTestResourceSpec]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testCTestResourceSpec" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib")
  set_tests_properties([=[CMakeLib.testCTestResourceSpec]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testCTestResourceSpec]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testCTestResourceSpec" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib")
  set_tests_properties([=[CMakeLib.testCTestResourceSpec]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testCTestResourceSpec]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testCTestResourceSpec" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib")
  set_tests_properties([=[CMakeLib.testCTestResourceSpec]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testCTestResourceSpec]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testCTestResourceSpec" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib")
  set_tests_properties([=[CMakeLib.testCTestResourceSpec]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testCTestResourceSpec]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testCTestResourceGroups]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testCTestResourceGroups")
  set_tests_properties([=[CMakeLib.testCTestResourceGroups]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testCTestResourceGroups]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testCTestResourceGroups")
  set_tests_properties([=[CMakeLib.testCTestResourceGroups]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testCTestResourceGroups]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testCTestResourceGroups")
  set_tests_properties([=[CMakeLib.testCTestResourceGroups]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testCTestResourceGroups]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testCTestResourceGroups")
  set_tests_properties([=[CMakeLib.testCTestResourceGroups]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testCTestResourceGroups]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testGccDepfileReader]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testGccDepfileReader" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib")
  set_tests_properties([=[CMakeLib.testGccDepfileReader]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testGccDepfileReader]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testGccDepfileReader" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib")
  set_tests_properties([=[CMakeLib.testGccDepfileReader]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testGccDepfileReader]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testGccDepfileReader" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib")
  set_tests_properties([=[CMakeLib.testGccDepfileReader]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testGccDepfileReader]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testGccDepfileReader" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib")
  set_tests_properties([=[CMakeLib.testGccDepfileReader]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testGccDepfileReader]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testGeneratedFileStream]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testGeneratedFileStream")
  set_tests_properties([=[CMakeLib.testGeneratedFileStream]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testGeneratedFileStream]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testGeneratedFileStream")
  set_tests_properties([=[CMakeLib.testGeneratedFileStream]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testGeneratedFileStream]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testGeneratedFileStream")
  set_tests_properties([=[CMakeLib.testGeneratedFileStream]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testGeneratedFileStream]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testGeneratedFileStream")
  set_tests_properties([=[CMakeLib.testGeneratedFileStream]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testGeneratedFileStream]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testJSONHelpers]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testJSONHelpers")
  set_tests_properties([=[CMakeLib.testJSONHelpers]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testJSONHelpers]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testJSONHelpers")
  set_tests_properties([=[CMakeLib.testJSONHelpers]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testJSONHelpers]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testJSONHelpers")
  set_tests_properties([=[CMakeLib.testJSONHelpers]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testJSONHelpers]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testJSONHelpers")
  set_tests_properties([=[CMakeLib.testJSONHelpers]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testJSONHelpers]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testRST]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testRST" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib")
  set_tests_properties([=[CMakeLib.testRST]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testRST]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testRST" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib")
  set_tests_properties([=[CMakeLib.testRST]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testRST]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testRST" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib")
  set_tests_properties([=[CMakeLib.testRST]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testRST]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testRST" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib")
  set_tests_properties([=[CMakeLib.testRST]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testRST]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testRange]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testRange")
  set_tests_properties([=[CMakeLib.testRange]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testRange]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testRange")
  set_tests_properties([=[CMakeLib.testRange]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testRange]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testRange")
  set_tests_properties([=[CMakeLib.testRange]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testRange]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testRange")
  set_tests_properties([=[CMakeLib.testRange]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testRange]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testOptional]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testOptional")
  set_tests_properties([=[CMakeLib.testOptional]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testOptional]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testOptional")
  set_tests_properties([=[CMakeLib.testOptional]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testOptional]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testOptional")
  set_tests_properties([=[CMakeLib.testOptional]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testOptional]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testOptional")
  set_tests_properties([=[CMakeLib.testOptional]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testOptional]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testString]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testString")
  set_tests_properties([=[CMakeLib.testString]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testString]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testString")
  set_tests_properties([=[CMakeLib.testString]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testString]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testString")
  set_tests_properties([=[CMakeLib.testString]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testString]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testString")
  set_tests_properties([=[CMakeLib.testString]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testString]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testStringAlgorithms]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testStringAlgorithms")
  set_tests_properties([=[CMakeLib.testStringAlgorithms]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testStringAlgorithms]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testStringAlgorithms")
  set_tests_properties([=[CMakeLib.testStringAlgorithms]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testStringAlgorithms]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testStringAlgorithms")
  set_tests_properties([=[CMakeLib.testStringAlgorithms]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testStringAlgorithms]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testStringAlgorithms")
  set_tests_properties([=[CMakeLib.testStringAlgorithms]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testStringAlgorithms]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testSystemTools]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testSystemTools")
  set_tests_properties([=[CMakeLib.testSystemTools]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testSystemTools]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testSystemTools")
  set_tests_properties([=[CMakeLib.testSystemTools]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testSystemTools]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testSystemTools")
  set_tests_properties([=[CMakeLib.testSystemTools]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testSystemTools]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testSystemTools")
  set_tests_properties([=[CMakeLib.testSystemTools]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testSystemTools]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testUTF8]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testUTF8")
  set_tests_properties([=[CMakeLib.testUTF8]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testUTF8]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testUTF8")
  set_tests_properties([=[CMakeLib.testUTF8]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testUTF8]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testUTF8")
  set_tests_properties([=[CMakeLib.testUTF8]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testUTF8]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testUTF8")
  set_tests_properties([=[CMakeLib.testUTF8]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testUTF8]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testXMLParser]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testXMLParser")
  set_tests_properties([=[CMakeLib.testXMLParser]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testXMLParser]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testXMLParser")
  set_tests_properties([=[CMakeLib.testXMLParser]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testXMLParser]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testXMLParser")
  set_tests_properties([=[CMakeLib.testXMLParser]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testXMLParser]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testXMLParser")
  set_tests_properties([=[CMakeLib.testXMLParser]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testXMLParser]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testXMLSafe]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testXMLSafe")
  set_tests_properties([=[CMakeLib.testXMLSafe]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testXMLSafe]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testXMLSafe")
  set_tests_properties([=[CMakeLib.testXMLSafe]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testXMLSafe]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testXMLSafe")
  set_tests_properties([=[CMakeLib.testXMLSafe]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testXMLSafe]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testXMLSafe")
  set_tests_properties([=[CMakeLib.testXMLSafe]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testXMLSafe]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testFindPackageCommand]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testFindPackageCommand")
  set_tests_properties([=[CMakeLib.testFindPackageCommand]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testFindPackageCommand]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testFindPackageCommand")
  set_tests_properties([=[CMakeLib.testFindPackageCommand]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testFindPackageCommand]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testFindPackageCommand")
  set_tests_properties([=[CMakeLib.testFindPackageCommand]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testFindPackageCommand]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testFindPackageCommand")
  set_tests_properties([=[CMakeLib.testFindPackageCommand]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testFindPackageCommand]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testUVProcessChain]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testUVProcessChain" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/testUVProcessChainHelper.exe")
  set_tests_properties([=[CMakeLib.testUVProcessChain]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testUVProcessChain]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testUVProcessChain" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/testUVProcessChainHelper.exe")
  set_tests_properties([=[CMakeLib.testUVProcessChain]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testUVProcessChain]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testUVProcessChain" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/testUVProcessChainHelper.exe")
  set_tests_properties([=[CMakeLib.testUVProcessChain]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testUVProcessChain]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testUVProcessChain" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/testUVProcessChainHelper.exe")
  set_tests_properties([=[CMakeLib.testUVProcessChain]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testUVProcessChain]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testUVRAII]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testUVRAII")
  set_tests_properties([=[CMakeLib.testUVRAII]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testUVRAII]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testUVRAII")
  set_tests_properties([=[CMakeLib.testUVRAII]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testUVRAII]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testUVRAII")
  set_tests_properties([=[CMakeLib.testUVRAII]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testUVRAII]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testUVRAII")
  set_tests_properties([=[CMakeLib.testUVRAII]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testUVRAII]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testUVStreambuf]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testUVStreambuf" "D:/Project/Application/FaceRecognitionPart/myenv/bin/Debug/cmake.exe")
  set_tests_properties([=[CMakeLib.testUVStreambuf]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testUVStreambuf]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testUVStreambuf" "D:/Project/Application/FaceRecognitionPart/myenv/bin/Release/cmake.exe")
  set_tests_properties([=[CMakeLib.testUVStreambuf]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testUVStreambuf]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testUVStreambuf" "D:/Project/Application/FaceRecognitionPart/myenv/bin/MinSizeRel/cmake.exe")
  set_tests_properties([=[CMakeLib.testUVStreambuf]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testUVStreambuf]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testUVStreambuf" "D:/Project/Application/FaceRecognitionPart/myenv/bin/RelWithDebInfo/cmake.exe")
  set_tests_properties([=[CMakeLib.testUVStreambuf]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testUVStreambuf]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testCMExtMemory]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testCMExtMemory")
  set_tests_properties([=[CMakeLib.testCMExtMemory]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testCMExtMemory]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testCMExtMemory")
  set_tests_properties([=[CMakeLib.testCMExtMemory]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testCMExtMemory]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testCMExtMemory")
  set_tests_properties([=[CMakeLib.testCMExtMemory]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testCMExtMemory]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testCMExtMemory")
  set_tests_properties([=[CMakeLib.testCMExtMemory]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testCMExtMemory]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testCMExtAlgorithm]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testCMExtAlgorithm")
  set_tests_properties([=[CMakeLib.testCMExtAlgorithm]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testCMExtAlgorithm]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testCMExtAlgorithm")
  set_tests_properties([=[CMakeLib.testCMExtAlgorithm]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testCMExtAlgorithm]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testCMExtAlgorithm")
  set_tests_properties([=[CMakeLib.testCMExtAlgorithm]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testCMExtAlgorithm]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testCMExtAlgorithm")
  set_tests_properties([=[CMakeLib.testCMExtAlgorithm]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testCMExtAlgorithm]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testCMExtEnumSet]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testCMExtEnumSet")
  set_tests_properties([=[CMakeLib.testCMExtEnumSet]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testCMExtEnumSet]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testCMExtEnumSet")
  set_tests_properties([=[CMakeLib.testCMExtEnumSet]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testCMExtEnumSet]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testCMExtEnumSet")
  set_tests_properties([=[CMakeLib.testCMExtEnumSet]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testCMExtEnumSet]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testCMExtEnumSet")
  set_tests_properties([=[CMakeLib.testCMExtEnumSet]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testCMExtEnumSet]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testList]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testList")
  set_tests_properties([=[CMakeLib.testList]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testList]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testList")
  set_tests_properties([=[CMakeLib.testList]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testList]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testList")
  set_tests_properties([=[CMakeLib.testList]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testList]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testList")
  set_tests_properties([=[CMakeLib.testList]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testList]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testDebuggerAdapter]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testDebuggerAdapter")
  set_tests_properties([=[CMakeLib.testDebuggerAdapter]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testDebuggerAdapter]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testDebuggerAdapter")
  set_tests_properties([=[CMakeLib.testDebuggerAdapter]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testDebuggerAdapter]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testDebuggerAdapter")
  set_tests_properties([=[CMakeLib.testDebuggerAdapter]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testDebuggerAdapter]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testDebuggerAdapter")
  set_tests_properties([=[CMakeLib.testDebuggerAdapter]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testDebuggerAdapter]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testDebuggerAdapterPipe]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testDebuggerAdapterPipe")
  set_tests_properties([=[CMakeLib.testDebuggerAdapterPipe]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testDebuggerAdapterPipe]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testDebuggerAdapterPipe")
  set_tests_properties([=[CMakeLib.testDebuggerAdapterPipe]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testDebuggerAdapterPipe]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testDebuggerAdapterPipe")
  set_tests_properties([=[CMakeLib.testDebuggerAdapterPipe]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testDebuggerAdapterPipe]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testDebuggerAdapterPipe")
  set_tests_properties([=[CMakeLib.testDebuggerAdapterPipe]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testDebuggerAdapterPipe]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testDebuggerBreakpointManager]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testDebuggerBreakpointManager")
  set_tests_properties([=[CMakeLib.testDebuggerBreakpointManager]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testDebuggerBreakpointManager]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testDebuggerBreakpointManager")
  set_tests_properties([=[CMakeLib.testDebuggerBreakpointManager]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testDebuggerBreakpointManager]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testDebuggerBreakpointManager")
  set_tests_properties([=[CMakeLib.testDebuggerBreakpointManager]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testDebuggerBreakpointManager]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testDebuggerBreakpointManager")
  set_tests_properties([=[CMakeLib.testDebuggerBreakpointManager]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testDebuggerBreakpointManager]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testDebuggerVariables]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testDebuggerVariables")
  set_tests_properties([=[CMakeLib.testDebuggerVariables]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testDebuggerVariables]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testDebuggerVariables")
  set_tests_properties([=[CMakeLib.testDebuggerVariables]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testDebuggerVariables]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testDebuggerVariables")
  set_tests_properties([=[CMakeLib.testDebuggerVariables]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testDebuggerVariables]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testDebuggerVariables")
  set_tests_properties([=[CMakeLib.testDebuggerVariables]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testDebuggerVariables]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testDebuggerVariablesHelper]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testDebuggerVariablesHelper")
  set_tests_properties([=[CMakeLib.testDebuggerVariablesHelper]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testDebuggerVariablesHelper]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testDebuggerVariablesHelper")
  set_tests_properties([=[CMakeLib.testDebuggerVariablesHelper]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testDebuggerVariablesHelper]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testDebuggerVariablesHelper")
  set_tests_properties([=[CMakeLib.testDebuggerVariablesHelper]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testDebuggerVariablesHelper]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testDebuggerVariablesHelper")
  set_tests_properties([=[CMakeLib.testDebuggerVariablesHelper]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testDebuggerVariablesHelper]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testDebuggerVariablesManager]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testDebuggerVariablesManager")
  set_tests_properties([=[CMakeLib.testDebuggerVariablesManager]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testDebuggerVariablesManager]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testDebuggerVariablesManager")
  set_tests_properties([=[CMakeLib.testDebuggerVariablesManager]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testDebuggerVariablesManager]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testDebuggerVariablesManager")
  set_tests_properties([=[CMakeLib.testDebuggerVariablesManager]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testDebuggerVariablesManager]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testDebuggerVariablesManager")
  set_tests_properties([=[CMakeLib.testDebuggerVariablesManager]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testDebuggerVariablesManager]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testVisualStudioSlnParser]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/CMakeLibTests.exe" "testVisualStudioSlnParser")
  set_tests_properties([=[CMakeLib.testVisualStudioSlnParser]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testVisualStudioSlnParser]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/CMakeLibTests.exe" "testVisualStudioSlnParser")
  set_tests_properties([=[CMakeLib.testVisualStudioSlnParser]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testVisualStudioSlnParser]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/CMakeLibTests.exe" "testVisualStudioSlnParser")
  set_tests_properties([=[CMakeLib.testVisualStudioSlnParser]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testVisualStudioSlnParser]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/CMakeLibTests.exe" "testVisualStudioSlnParser")
  set_tests_properties([=[CMakeLib.testVisualStudioSlnParser]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;79;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testVisualStudioSlnParser]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testDebuggerNamedPipe-Project]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/testDebuggerNamedPipe.exe" "D:/Project/Application/FaceRecognitionPart/myenv/bin/Debug/cmake.exe" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/DebuggerSample" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/DebuggerSample")
  set_tests_properties([=[CMakeLib.testDebuggerNamedPipe-Project]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;102;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testDebuggerNamedPipe-Project]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/testDebuggerNamedPipe.exe" "D:/Project/Application/FaceRecognitionPart/myenv/bin/Release/cmake.exe" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/DebuggerSample" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/DebuggerSample")
  set_tests_properties([=[CMakeLib.testDebuggerNamedPipe-Project]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;102;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testDebuggerNamedPipe-Project]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/testDebuggerNamedPipe.exe" "D:/Project/Application/FaceRecognitionPart/myenv/bin/MinSizeRel/cmake.exe" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/DebuggerSample" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/DebuggerSample")
  set_tests_properties([=[CMakeLib.testDebuggerNamedPipe-Project]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;102;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testDebuggerNamedPipe-Project]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/testDebuggerNamedPipe.exe" "D:/Project/Application/FaceRecognitionPart/myenv/bin/RelWithDebInfo/cmake.exe" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/DebuggerSample" "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/DebuggerSample")
  set_tests_properties([=[CMakeLib.testDebuggerNamedPipe-Project]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;102;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testDebuggerNamedPipe-Project]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CMakeLib.testDebuggerNamedPipe-Script]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Debug/testDebuggerNamedPipe.exe" "D:/Project/Application/FaceRecognitionPart/myenv/bin/Debug/cmake.exe" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/DebuggerSample/script.cmake")
  set_tests_properties([=[CMakeLib.testDebuggerNamedPipe-Script]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;102;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CMakeLib.testDebuggerNamedPipe-Script]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/Release/testDebuggerNamedPipe.exe" "D:/Project/Application/FaceRecognitionPart/myenv/bin/Release/cmake.exe" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/DebuggerSample/script.cmake")
  set_tests_properties([=[CMakeLib.testDebuggerNamedPipe-Script]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;102;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CMakeLib.testDebuggerNamedPipe-Script]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/MinSizeRel/testDebuggerNamedPipe.exe" "D:/Project/Application/FaceRecognitionPart/myenv/bin/MinSizeRel/cmake.exe" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/DebuggerSample/script.cmake")
  set_tests_properties([=[CMakeLib.testDebuggerNamedPipe-Script]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;102;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CMakeLib.testDebuggerNamedPipe-Script]=] "D:/Project/Application/FaceRecognitionPart/myenv/Tests/CMakeLib/RelWithDebInfo/testDebuggerNamedPipe.exe" "D:/Project/Application/FaceRecognitionPart/myenv/bin/RelWithDebInfo/cmake.exe" "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/DebuggerSample/script.cmake")
  set_tests_properties([=[CMakeLib.testDebuggerNamedPipe-Script]=] PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;102;add_test;D:/Project/Application/FaceRecognitionPart/cmake-3.27.7/Tests/CMakeLib/CMakeLists.txt;0;")
else()
  add_test([=[CMakeLib.testDebuggerNamedPipe-Script]=] NOT_AVAILABLE)
endif()
subdirs("PseudoMemcheck")
